// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: areas.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProjectsByArea = `-- name: CountProjectsByArea :one
SELECT COUNT(*) FROM projects WHERE subarea_id IN (SELECT id FROM subareas WHERE area_id = ?)
`

func (q *Queries) CountProjectsByArea(ctx context.Context, areaID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByArea, areaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubareasByArea = `-- name: CountSubareasByArea :one
SELECT COUNT(*) FROM subareas WHERE area_id = ?
`

func (q *Queries) CountSubareasByArea(ctx context.Context, areaID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubareasByArea, areaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByArea = `-- name: CountTasksByArea :one
SELECT COUNT(*) FROM tasks WHERE project_id IN (
    SELECT id FROM projects WHERE subarea_id IN (SELECT id FROM subareas WHERE area_id = ?)
)
`

func (q *Queries) CountTasksByArea(ctx context.Context, areaID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByArea, areaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArea = `-- name: CreateArea :one
INSERT INTO areas (id, name, color, sort_order, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, color, sort_order, created_at, updated_at, deleted_at
`

type CreateAreaParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	SortOrder int64          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt interface{}    `json:"deleted_at"`
}

type CreateAreaRow struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	SortOrder int64          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt interface{}    `json:"deleted_at"`
}

func (q *Queries) CreateArea(ctx context.Context, arg CreateAreaParams) (CreateAreaRow, error) {
	row := q.db.QueryRowContext(ctx, createArea,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i CreateAreaRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProjectsBySubarea = `-- name: DeleteProjectsBySubarea :exec
DELETE FROM projects WHERE subarea_id IN (SELECT id FROM subareas WHERE area_id = ?)
`

func (q *Queries) DeleteProjectsBySubarea(ctx context.Context, areaID string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectsBySubarea, areaID)
	return err
}

const deleteSubareasByArea = `-- name: DeleteSubareasByArea :exec
DELETE FROM subareas WHERE area_id = ?
`

func (q *Queries) DeleteSubareasByArea(ctx context.Context, areaID string) error {
	_, err := q.db.ExecContext(ctx, deleteSubareasByArea, areaID)
	return err
}

const deleteTasksByProject = `-- name: DeleteTasksByProject :exec
DELETE FROM tasks WHERE project_id IN (
    SELECT id FROM projects WHERE subarea_id IN (SELECT id FROM subareas WHERE area_id = ?)
)
`

func (q *Queries) DeleteTasksByProject(ctx context.Context, areaID string) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByProject, areaID)
	return err
}

const getAreaByID = `-- name: GetAreaByID :one
SELECT id, name, color, sort_order, created_at, updated_at, deleted_at
FROM areas
WHERE id = ? AND deleted_at IS NULL
`

type GetAreaByIDRow struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	SortOrder int64          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt interface{}    `json:"deleted_at"`
}

func (q *Queries) GetAreaByID(ctx context.Context, id string) (GetAreaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAreaByID, id)
	var i GetAreaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteArea = `-- name: HardDeleteArea :exec
DELETE FROM areas
WHERE id = ?
`

func (q *Queries) HardDeleteArea(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteArea, id)
	return err
}

const listAreas = `-- name: ListAreas :many
SELECT id, name, color, sort_order, created_at, updated_at, deleted_at
FROM areas
WHERE deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListAreasRow struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	SortOrder int64          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt interface{}    `json:"deleted_at"`
}

func (q *Queries) ListAreas(ctx context.Context) ([]ListAreasRow, error) {
	rows, err := q.db.QueryContext(ctx, listAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAreasRow{}
	for rows.Next() {
		var i ListAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteArea = `-- name: SoftDeleteArea :one
UPDATE areas
SET deleted_at = ?
WHERE id = ?
RETURNING id, name, color, sort_order, created_at, updated_at, deleted_at
`

type SoftDeleteAreaParams struct {
	DeletedAt interface{} `json:"deleted_at"`
	ID        string      `json:"id"`
}

type SoftDeleteAreaRow struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	SortOrder int64          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt interface{}    `json:"deleted_at"`
}

func (q *Queries) SoftDeleteArea(ctx context.Context, arg SoftDeleteAreaParams) (SoftDeleteAreaRow, error) {
	row := q.db.QueryRowContext(ctx, softDeleteArea, arg.DeletedAt, arg.ID)
	var i SoftDeleteAreaRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateArea = `-- name: UpdateArea :one
UPDATE areas
SET name = ?, color = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, color, sort_order, created_at, updated_at, deleted_at
`

type UpdateAreaParams struct {
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

type UpdateAreaRow struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	SortOrder int64          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt interface{}    `json:"deleted_at"`
}

func (q *Queries) UpdateArea(ctx context.Context, arg UpdateAreaParams) (UpdateAreaRow, error) {
	row := q.db.QueryRowContext(ctx, updateArea,
		arg.Name,
		arg.Color,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateAreaRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAreaSortOrder = `-- name: UpdateAreaSortOrder :exec
UPDATE areas
SET sort_order = ?, updated_at = ?
WHERE id = ?
`

type UpdateAreaSortOrderParams struct {
	SortOrder int64     `json:"sort_order"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateAreaSortOrder(ctx context.Context, arg UpdateAreaSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateAreaSortOrder, arg.SortOrder, arg.UpdatedAt, arg.ID)
	return err
}
