// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Area struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt *time.Time     `json:"deleted_at"`
	SortOrder int64          `json:"sort_order"`
}

type Project struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Goal        sql.NullString `json:"goal"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	Progress    int64          `json:"progress"`
	Deadline    *time.Time     `json:"deadline"`
	Color       sql.NullString `json:"color"`
	ParentID    sql.NullString `json:"parent_id"`
	SubareaID   sql.NullString `json:"subarea_id"`
	Position    int64          `json:"position"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt *time.Time     `json:"completed_at"`
	DeletedAt   *time.Time     `json:"deleted_at"`
}

type Subarea struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	AreaID    string         `json:"area_id"`
	Color     sql.NullString `json:"color"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt *time.Time     `json:"deleted_at"`
}

type Task struct {
	ID                string         `json:"id"`
	ProjectID         string         `json:"project_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	StartDate         *time.Time     `json:"start_date"`
	Deadline          *time.Time     `json:"deadline"`
	Priority          string         `json:"priority"`
	Context           sql.NullString `json:"context"`
	EstimatedDuration sql.NullInt64  `json:"estimated_duration"`
	Status            string         `json:"status"`
	IsNext            int64          `json:"is_next"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         *time.Time     `json:"deleted_at"`
}
