// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProjectsByParent = `-- name: CountProjectsByParent :one
SELECT COUNT(*) FROM projects WHERE parent_id = ?
`

func (q *Queries) CountProjectsByParent(ctx context.Context, parentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByParent, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByProject = `-- name: CountTasksByProject :one
SELECT COUNT(*) FROM tasks WHERE project_id = ?
`

func (q *Queries) CountTasksByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
`

type CreateProjectParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Goal        sql.NullString `json:"goal"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	Progress    int64          `json:"progress"`
	Deadline    interface{}    `json:"deadline"`
	Color       sql.NullString `json:"color"`
	ParentID    sql.NullString `json:"parent_id"`
	SubareaID   sql.NullString `json:"subarea_id"`
	Position    int64          `json:"position"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt interface{}    `json:"completed_at"`
	DeletedAt   interface{}    `json:"deleted_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Goal,
		arg.Status,
		arg.Priority,
		arg.Progress,
		arg.Deadline,
		arg.Color,
		arg.ParentID,
		arg.SubareaID,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.DeletedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.Deadline,
		&i.Color,
		&i.ParentID,
		&i.SubareaID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
FROM projects
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.Deadline,
		&i.Color,
		&i.ParentID,
		&i.SubareaID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectsByStatus = `-- name: GetProjectsByStatus :many
SELECT id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
FROM projects
WHERE status = ? AND deleted_at IS NULL
ORDER BY priority DESC, deadline ASC, name ASC
`

func (q *Queries) GetProjectsByStatus(ctx context.Context, status string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Goal,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.Deadline,
			&i.Color,
			&i.ParentID,
			&i.SubareaID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) HardDeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteProject, id)
	return err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
FROM projects
WHERE deleted_at IS NULL
ORDER BY position ASC, name ASC
`

func (q *Queries) ListAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Goal,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.Deadline,
			&i.Color,
			&i.ParentID,
			&i.SubareaID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByParent = `-- name: ListProjectsByParent :many
SELECT id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
FROM projects
WHERE parent_id = ? AND deleted_at IS NULL
ORDER BY position ASC, name ASC
`

func (q *Queries) ListProjectsByParent(ctx context.Context, parentID sql.NullString) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Goal,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.Deadline,
			&i.Color,
			&i.ParentID,
			&i.SubareaID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByPriority = `-- name: ListProjectsByPriority :many
SELECT id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
FROM projects
WHERE priority = ? AND deleted_at IS NULL
ORDER BY priority DESC, deadline ASC, name ASC
`

func (q *Queries) ListProjectsByPriority(ctx context.Context, priority string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Goal,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.Deadline,
			&i.Color,
			&i.ParentID,
			&i.SubareaID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsBySubarea = `-- name: ListProjectsBySubarea :many
SELECT id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
FROM projects
WHERE subarea_id = ? AND deleted_at IS NULL
ORDER BY position ASC, name ASC
`

func (q *Queries) ListProjectsBySubarea(ctx context.Context, subareaID sql.NullString) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsBySubarea, subareaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Goal,
			&i.Status,
			&i.Priority,
			&i.Progress,
			&i.Deadline,
			&i.Color,
			&i.ParentID,
			&i.SubareaID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :one
UPDATE projects
SET deleted_at = ?
WHERE id = ?
RETURNING id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
`

type SoftDeleteProjectParams struct {
	DeletedAt interface{} `json:"deleted_at"`
	ID        string      `json:"id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, softDeleteProject, arg.DeletedAt, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.Deadline,
		&i.Color,
		&i.ParentID,
		&i.SubareaID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?, description = ?, goal = ?, status = ?, priority = ?, progress = ?, deadline = ?, color = ?, parent_id = ?, subarea_id = ?, position = ?, updated_at = ?, completed_at = ?
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, description, goal, status, priority, progress, deadline, color, parent_id, subarea_id, position, created_at, updated_at, completed_at, deleted_at
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Goal        sql.NullString `json:"goal"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	Progress    int64          `json:"progress"`
	Deadline    interface{}    `json:"deadline"`
	Color       sql.NullString `json:"color"`
	ParentID    sql.NullString `json:"parent_id"`
	SubareaID   sql.NullString `json:"subarea_id"`
	Position    int64          `json:"position"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CompletedAt interface{}    `json:"completed_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Goal,
		arg.Status,
		arg.Priority,
		arg.Progress,
		arg.Deadline,
		arg.Color,
		arg.ParentID,
		arg.SubareaID,
		arg.Position,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Status,
		&i.Priority,
		&i.Progress,
		&i.Deadline,
		&i.Color,
		&i.ParentID,
		&i.SubareaID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}
