// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountProjectsByArea(ctx context.Context, areaID string) (int64, error)
	CountProjectsByParent(ctx context.Context, parentID sql.NullString) (int64, error)
	CountProjectsBySubarea(ctx context.Context, subareaID sql.NullString) (int64, error)
	CountSubareasByArea(ctx context.Context, areaID string) (int64, error)
	CountTasksByArea(ctx context.Context, areaID string) (int64, error)
	CountTasksByProject(ctx context.Context, projectID string) (int64, error)
	CreateArea(ctx context.Context, arg CreateAreaParams) (CreateAreaRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSubarea(ctx context.Context, arg CreateSubareaParams) (Subarea, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteProjectsByParentID(ctx context.Context, parentID sql.NullString) error
	DeleteProjectsBySubarea(ctx context.Context, areaID string) error
	DeleteProjectsBySubareaID(ctx context.Context, subareaID sql.NullString) error
	DeleteSubareasByArea(ctx context.Context, areaID string) error
	DeleteTasksByProject(ctx context.Context, areaID string) error
	DeleteTasksByProjectID(ctx context.Context, projectID string) error
	DeleteTasksBySubareaID(ctx context.Context, subareaID sql.NullString) error
	GetAreaByID(ctx context.Context, id string) (GetAreaByIDRow, error)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	GetProjectsByStatus(ctx context.Context, status string) ([]Project, error)
	GetSubareaByID(ctx context.Context, id string) (Subarea, error)
	GetTaskByID(ctx context.Context, id string) (Task, error)
	HardDeleteArea(ctx context.Context, id string) error
	HardDeleteProject(ctx context.Context, id string) error
	HardDeleteSubarea(ctx context.Context, id string) error
	HardDeleteTask(ctx context.Context, id string) error
	ListAllProjects(ctx context.Context) ([]Project, error)
	ListAllSubareas(ctx context.Context) ([]Subarea, error)
	ListAllTasks(ctx context.Context) ([]Task, error)
	ListAreas(ctx context.Context) ([]ListAreasRow, error)
	ListNextTasks(ctx context.Context) ([]Task, error)
	ListProjectsByParent(ctx context.Context, parentID sql.NullString) ([]Project, error)
	ListProjectsByPriority(ctx context.Context, priority string) ([]Project, error)
	ListProjectsBySubarea(ctx context.Context, subareaID sql.NullString) ([]Project, error)
	ListProjectsBySubareaRecursive(ctx context.Context, subareaID sql.NullString) ([]ListProjectsBySubareaRecursiveRow, error)
	ListSubareasByArea(ctx context.Context, areaID string) ([]Subarea, error)
	ListTasksByPriority(ctx context.Context, priority string) ([]Task, error)
	ListTasksByProject(ctx context.Context, projectID string) ([]Task, error)
	ListTasksByStatus(ctx context.Context, status string) ([]Task, error)
	SoftDeleteArea(ctx context.Context, arg SoftDeleteAreaParams) (SoftDeleteAreaRow, error)
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (Project, error)
	SoftDeleteSubarea(ctx context.Context, arg SoftDeleteSubareaParams) (Subarea, error)
	SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) (Task, error)
	ToggleIsNext(ctx context.Context, arg ToggleIsNextParams) (Task, error)
	UpdateArea(ctx context.Context, arg UpdateAreaParams) (UpdateAreaRow, error)
	UpdateAreaSortOrder(ctx context.Context, arg UpdateAreaSortOrderParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSubarea(ctx context.Context, arg UpdateSubareaParams) (Subarea, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
