// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subareas.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProjectsBySubarea = `-- name: CountProjectsBySubarea :one
SELECT COUNT(*) FROM projects WHERE subarea_id = ?
`

func (q *Queries) CountProjectsBySubarea(ctx context.Context, subareaID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsBySubarea, subareaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubarea = `-- name: CreateSubarea :one
INSERT INTO subareas (id, name, area_id, color, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, area_id, color, created_at, updated_at, deleted_at
`

type CreateSubareaParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	AreaID    string         `json:"area_id"`
	Color     sql.NullString `json:"color"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt *time.Time     `json:"deleted_at"`
}

func (q *Queries) CreateSubarea(ctx context.Context, arg CreateSubareaParams) (Subarea, error) {
	row := q.db.QueryRowContext(ctx, createSubarea,
		arg.ID,
		arg.Name,
		arg.AreaID,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i Subarea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProjectsBySubareaID = `-- name: DeleteProjectsBySubareaID :exec
DELETE FROM projects WHERE subarea_id = ?
`

func (q *Queries) DeleteProjectsBySubareaID(ctx context.Context, subareaID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteProjectsBySubareaID, subareaID)
	return err
}

const deleteTasksBySubareaID = `-- name: DeleteTasksBySubareaID :exec
DELETE FROM tasks WHERE project_id IN (SELECT id FROM projects WHERE subarea_id = ?)
`

func (q *Queries) DeleteTasksBySubareaID(ctx context.Context, subareaID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTasksBySubareaID, subareaID)
	return err
}

const getSubareaByID = `-- name: GetSubareaByID :one
SELECT id, name, area_id, color, created_at, updated_at, deleted_at
FROM subareas
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetSubareaByID(ctx context.Context, id string) (Subarea, error) {
	row := q.db.QueryRowContext(ctx, getSubareaByID, id)
	var i Subarea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteSubarea = `-- name: HardDeleteSubarea :exec
DELETE FROM subareas WHERE id = ?
`

func (q *Queries) HardDeleteSubarea(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteSubarea, id)
	return err
}

const listAllSubareas = `-- name: ListAllSubareas :many
SELECT id, name, area_id, color, created_at, updated_at, deleted_at
FROM subareas
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListAllSubareas(ctx context.Context) ([]Subarea, error) {
	rows, err := q.db.QueryContext(ctx, listAllSubareas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subarea{}
	for rows.Next() {
		var i Subarea
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AreaID,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubareasByArea = `-- name: ListSubareasByArea :many
SELECT id, name, area_id, color, created_at, updated_at, deleted_at
FROM subareas
WHERE area_id = ? AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListSubareasByArea(ctx context.Context, areaID string) ([]Subarea, error) {
	rows, err := q.db.QueryContext(ctx, listSubareasByArea, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subarea{}
	for rows.Next() {
		var i Subarea
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AreaID,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSubarea = `-- name: SoftDeleteSubarea :one
UPDATE subareas
SET deleted_at = ?
WHERE id = ?
RETURNING id, name, area_id, color, created_at, updated_at, deleted_at
`

type SoftDeleteSubareaParams struct {
	DeletedAt *time.Time `json:"deleted_at"`
	ID        string     `json:"id"`
}

func (q *Queries) SoftDeleteSubarea(ctx context.Context, arg SoftDeleteSubareaParams) (Subarea, error) {
	row := q.db.QueryRowContext(ctx, softDeleteSubarea, arg.DeletedAt, arg.ID)
	var i Subarea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSubarea = `-- name: UpdateSubarea :one
UPDATE subareas
SET name = ?, area_id = ?, color = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, area_id, color, created_at, updated_at, deleted_at
`

type UpdateSubareaParams struct {
	Name      string         `json:"name"`
	AreaID    string         `json:"area_id"`
	Color     sql.NullString `json:"color"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateSubarea(ctx context.Context, arg UpdateSubareaParams) (Subarea, error) {
	row := q.db.QueryRowContext(ctx, updateSubarea,
		arg.Name,
		arg.AreaID,
		arg.Color,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Subarea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
