// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ID                string         `json:"id"`
	ProjectID         string         `json:"project_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	StartDate         interface{}    `json:"start_date"`
	Deadline          interface{}    `json:"deadline"`
	Priority          string         `json:"priority"`
	Context           sql.NullString `json:"context"`
	EstimatedDuration sql.NullInt64  `json:"estimated_duration"`
	Status            string         `json:"status"`
	IsNext            int64          `json:"is_next"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         interface{}    `json:"deleted_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.Deadline,
		arg.Priority,
		arg.Context,
		arg.EstimatedDuration,
		arg.Status,
		arg.IsNext,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.Deadline,
		&i.Priority,
		&i.Context,
		&i.EstimatedDuration,
		&i.Status,
		&i.IsNext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
FROM tasks
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.Deadline,
		&i.Priority,
		&i.Context,
		&i.EstimatedDuration,
		&i.Status,
		&i.IsNext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteTask = `-- name: HardDeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) HardDeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteTask, id)
	return err
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
FROM tasks
WHERE deleted_at IS NULL
ORDER BY is_next DESC, priority DESC, deadline ASC, title ASC
`

func (q *Queries) ListAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.Deadline,
			&i.Priority,
			&i.Context,
			&i.EstimatedDuration,
			&i.Status,
			&i.IsNext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNextTasks = `-- name: ListNextTasks :many
SELECT id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
FROM tasks
WHERE is_next = 1 AND deleted_at IS NULL
ORDER BY priority DESC, deadline ASC, title ASC
`

func (q *Queries) ListNextTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listNextTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.Deadline,
			&i.Priority,
			&i.Context,
			&i.EstimatedDuration,
			&i.Status,
			&i.IsNext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPriority = `-- name: ListTasksByPriority :many
SELECT id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
FROM tasks
WHERE priority = ? AND deleted_at IS NULL
ORDER BY is_next DESC, deadline ASC, title ASC
`

func (q *Queries) ListTasksByPriority(ctx context.Context, priority string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.Deadline,
			&i.Priority,
			&i.Context,
			&i.EstimatedDuration,
			&i.Status,
			&i.IsNext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
FROM tasks
WHERE project_id = ? AND deleted_at IS NULL
ORDER BY is_next DESC, priority DESC, deadline ASC, title ASC
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.Deadline,
			&i.Priority,
			&i.Context,
			&i.EstimatedDuration,
			&i.Status,
			&i.IsNext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
FROM tasks
WHERE status = ? AND deleted_at IS NULL
ORDER BY is_next DESC, priority DESC, deadline ASC, title ASC
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.Deadline,
			&i.Priority,
			&i.Context,
			&i.EstimatedDuration,
			&i.Status,
			&i.IsNext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :one
UPDATE tasks
SET deleted_at = ?
WHERE id = ?
RETURNING id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
`

type SoftDeleteTaskParams struct {
	DeletedAt interface{} `json:"deleted_at"`
	ID        string      `json:"id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, softDeleteTask, arg.DeletedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.Deadline,
		&i.Priority,
		&i.Context,
		&i.EstimatedDuration,
		&i.Status,
		&i.IsNext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const toggleIsNext = `-- name: ToggleIsNext :one
UPDATE tasks
SET is_next = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
RETURNING id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
`

type ToggleIsNextParams struct {
	IsNext    int64     `json:"is_next"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) ToggleIsNext(ctx context.Context, arg ToggleIsNextParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, toggleIsNext, arg.IsNext, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.Deadline,
		&i.Priority,
		&i.Context,
		&i.EstimatedDuration,
		&i.Status,
		&i.IsNext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = ?, description = ?, start_date = ?, deadline = ?, priority = ?, context = ?, estimated_duration = ?, status = ?, is_next = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
RETURNING id, project_id, title, description, start_date, deadline, priority, context, estimated_duration, status, is_next, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	StartDate         interface{}    `json:"start_date"`
	Deadline          interface{}    `json:"deadline"`
	Priority          string         `json:"priority"`
	Context           sql.NullString `json:"context"`
	EstimatedDuration sql.NullInt64  `json:"estimated_duration"`
	Status            string         `json:"status"`
	IsNext            int64          `json:"is_next"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.Deadline,
		arg.Priority,
		arg.Context,
		arg.EstimatedDuration,
		arg.Status,
		arg.IsNext,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.Deadline,
		&i.Priority,
		&i.Context,
		&i.EstimatedDuration,
		&i.Status,
		&i.IsNext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
